In [1]:
import numpy as np

In [3]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [5]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [6]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [9]:
np.array([1.0,3,4]) + 100

array([101., 103., 104.])

In [10]:
a = np.random.randn(5)
print(a)

[-0.66557867 -0.19449279 -0.40386289  0.371029   -0.60079026]


In [11]:
a.shape

(5,)

In [12]:
a.T.shape

(5,)

In [13]:
print(np.dot(a, a.T))

1.1425391059306242


In [14]:
#It is very hard to debug code above, because the dimension of the vector
#is difficult to identify after operation

In [15]:
# In order to avoid any complication, we should explicit the shape of the array we are creating

In [17]:
a = np.random.randn(5,1)
print(a)

[[ 0.60846012]
 [ 0.41782065]
 [-1.71899392]
 [-0.63400718]
 [-1.39581283]]


In [18]:
print(a.T)

[[ 0.60846012  0.41782065 -1.71899392 -0.63400718 -1.39581283]]


In [20]:
print(np.dot(a, a.T))

[[ 0.37022372  0.25422721 -1.04593925 -0.38576809 -0.84929645]
 [ 0.25422721  0.1745741  -0.71823116 -0.2649013  -0.58319943]
 [-1.04593925 -0.71823116  2.95494009  1.08985449  2.39939376]
 [-0.38576809 -0.2649013   1.08985449  0.40196511  0.88495536]
 [-0.84929645 -0.58319943  2.39939376  0.88495536  1.94829345]]


In [21]:
assert(a.shape == (5,1))

In [22]:
assert(a.shape == (1,5))

AssertionError: 

In [23]:
a=np.random.randn(12288, 150)
b=np.random.randn(150, 45)
print(np.dot(a, b).shape)

(12288, 45)


In [24]:
print(a)

[[-1.08079152  0.2184997  -0.99386166 ... -0.08888122 -1.29975557
   1.28704355]
 [-0.0823335   1.04939016 -1.63019274 ...  0.21452901  0.24280755
   0.88566286]
 [ 1.84070237  0.88891183  0.1010927  ... -1.34510805  0.52833169
   0.9133158 ]
 ...
 [-2.28612035 -1.5356022   0.20221357 ...  0.18811677  1.61227022
   0.56133266]
 [-1.59169246 -1.3704846  -1.52547817 ... -0.03292352  1.12562555
   0.02074091]
 [-0.72762078 -0.77498318 -1.0959191  ... -1.15172282 -2.7085336
   1.02046007]]


In [25]:
np.random.randn(1,5)

array([[-0.79810031, -2.28242163,  1.89898347, -0.13851871, -0.10357773]])

In [26]:
np.random.randn(5,1)

array([[ 2.20310947],
       [-0.2475076 ],
       [ 0.85862428],
       [-0.09990341],
       [-2.64140347]])

In [31]:
np.random.randn(4,3)

array([[ 0.67317983, -1.39070797,  1.46231484],
       [ 0.10205084, -1.45442043, -1.60591103],
       [ 0.80424577, -1.62873363, -0.09706704],
       [-2.61014525,  1.46278221, -0.31935035]])

In [32]:
np.random.randn(3,3) * np.random.rand(3,1)

array([[ 0.05842578,  0.04124894,  0.1663469 ],
       [-0.3825631 , -1.06624428, -2.08973661],
       [-0.02988694,  0.04741788,  0.38121681]])

In [40]:
(np.random.randn(2,3) + np.random.randn(2,1)).shape

(2, 3)

In [42]:
(np.random.randn(4,3) * np.random.randn(3,2)).shape

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [44]:
a = np.array([[2,1],[1,3]])
print(a)

[[2 1]
 [1 3]]


In [45]:
a*a

array([[4, 1],
       [1, 9]])

In [50]:
a=np.random.randn(3,4)
b=np.random.randn(4,1)
a*b.T

array([[ 0.22002571,  1.77391006, -0.59148403,  0.09594566],
       [-0.26007544,  0.62947179, -1.52183958, -0.78708555],
       [-1.0777614 ,  0.00433343, -0.69249274, -0.20219255]])

In [51]:
a=np.random.randn(3,3)
b=np.random.randn(3,1)
c=a*b
print(c.shape)

(3, 3)


In [53]:
#(ab + ac -(b+c))

In [54]:
# => a(b+c)-(b+c)

In [ ]:
# => (a-1)*(b+c)